### ISSUE TITLE
Move or remove brainstorming question about analogies and heuristics

### ISSUE THREAD

**Issue by gvwilson** [datacamp/authoring#25]
Lynne Williams: this was hard to answer early, would probably have been easier later on.

**Comment by gvwilson** [comment]
@richierocks @ismayc @dhavide do you think this one is worth keeping?

**Comment by ismayc** [comment]
@gvwilson I think I’d move it to after the course outline if we do keep it. The vast majority of instructors I have worked with skip it early on and come back to them later on.

**Comment by gvwilson** [comment]
@richierocks @dhavide one vote to drop or move - how do you feel?

**Comment by richierocks** [comment]
I vote keep it where it is. This is something instructors need to brew in the back of their minds for a while, so best to ask the the question early (in order to make it possible to answer later on).

In the interest of trying to target our work, I'm going to make an executive decision and close this issue; but feel free to reopen if you have strong objections.
