### ISSUE TITLE
Style guides are missing

### ISSUE THREAD

**Issue by sumedh10** [datacamp/authoring#38]
They previously existed at 

https://www.datacamp.com/teach/documentation#tab_style_guide_python 

https://www.datacamp.com/teach/documentation#tab_style_guide_r

**Comment by sumedh10** [comment]
@gvwilson These were style guides specific to writing R and Python code.

**Comment by richierocks** [comment]
I had a look in https://github.com/datacamp/teach-documentation, but I don't think that ever had a  Python style guide in it. That repo suggests that Teach documentation was moved to the [teach-app](https://github.com/datacamp/teach-app) repo, but I can't see anything in their anymore. 

Since Python has a decent semi-official style guide, https://www.python.org/dev/peps/pep-0008, we could just link to that.

For SQL, we've never had a style guide, but I believe https://www.sqlstyle.guide was used unofficially by @ismayc.

For R, I'd also be happy linking to a [decent external style guide](https://4dpiecharts.com/r-code-style-guide).

I'm not sure that the Shell curriculum needs a style guide, but I found this: https://google.github.io/styleguide/shell.xml

**Comment by ismayc** [comment]
Yep. I used https://www.sqlstyle.guide where feasible for our platform.

**Comment by ismayc** [comment]
I think the only thing that stands out on the R guide is the use of comments after the code on the same line.

**Comment by ncarchedi** [comment]
This is the only page I'm aware of, but was last edited in 2015 and is now archived: https://github.com/datacamp/teach-documentation/blob/master/style_guide.md

**Comment by hugobowne** [comment]
@richierocks there was a live python style guide that @vincentvankrunkelsven wrote in early 2016. I remember it well but I don't know where it is any more.

**Comment by richierocks** [comment]
added
