### ISSUE TITLE
level 2 header not always used for exercise title

### ISSUE THREAD

**Issue by gor181** [datacamp/authoring#51]
@machow commented on [Wed Dec 13 2017](https://github.com/datacamp/teach-bugs/issues/113)

## Summary of the issue

When two hashmarks are used to indicate a header, teach uses it as an exercise title. When `----` is used to indicate a level 2 header, teach thinks it is demarcating a new exercise.

What is the relationship between the teach exercise grammar and markdown supposed to be?

## Minimally reproducible example

Replace two hash marks with `---` underneath.

![image](https://user-images.githubusercontent.com/2574498/33959226-c8faec26-e014-11e7-8969-5fecb441bed3.png)

---

@machow commented on [Wed Dec 13 2017](https://github.com/datacamp/teach-bugs/issues/113#issuecomment-351516699)

Wait, I think I understand. It looks like `##` and `---*` define the opening and closing of an exercise block now. Might be useful to clarify in the authoring book, since it says that `##` is a header, but does not mention how to separate exercises.

http://authoring.datacamp.com/courses/exercises/

---

@gor181 commented on [Thu Dec 14 2017](https://github.com/datacamp/teach-bugs/issues/113#issuecomment-351557088)

Exactly each exercise starts with `--- type:` (old syntax) or `---` followed by a title for new syntax.
Moving this task there thanks

**Comment by richierocks** [comment]
not an authoring issue

**Comment by machow** [comment]
@richierocks my main concern in raising this issue is that the authoring docs do not specify how to separate exercises. From what I can understand each exercise is defined by

* three dashes at the top `---`
* a title block, that must begin with two hashmarks `## some title`
* a yaml field

authoring does not mention that exercises must start with three dashes. This was confusing to me, because `##` is a level 2 markdown heading, but so is `---`
